Numpy é uma biblioteca é principalmente usada para trabalhar com numeros, matrizes e arrays e grandes dados numéricos conceitos usados em ML.

In [34]:
import numpy as np
#criação de arrays usando numpy
print(np.zeros(3))
#com zeros
print(np.ones(3))
#com uns
print(np.full(3,4))
# Nesse exemplo o primeiro espaço é usado para definir o tamanho da array, e o segundo espaço o numero que estara preenchendo.
#É possivel transformar uma lista numerica em um array de Numpy.
array_teste = np.array([1,5,8,9,7,61,54])
# Tambem possui indexação nesses arrays
print(array_teste[3],array_teste[0])
# Criação de arrays usando ranges indexação começa sempre em 0 então é ultimo numero -1, com regras parecidas com range com primeiro espaço sendo o de começo e o segundo o tanto até onde vai e o terceiro 'step' como usado com pular mas não é possivel usar -1 como reverse .arange(start,stop,step,dtype) e a formatação dos dados podendo ser inteiro ou float.
print(np.arange(1,11,2))
# Criação de arrays usando .linspace com o primeiro numero sendo sobre o começo, o segundo o ultimo e o terceiro a quantidade de numeros entre 1 e outro.
print(np.linspace(1,100,7))

[0. 0. 0.]
[1. 1. 1.]
[4 4 4]
9 1
[1 3 5 7 9]
[  1.   17.5  34.   50.5  67.   83.5 100. ]


In [1]:
import pandas as pd


In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
